apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-docker-python-rhtap-three-component-scenarios-wtcx
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-cwuf-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-wtcx@sha256:62585bb810acdd2543ce228b8c42eaebeb5845e50f9a9bbbe287dfd8b5ea0176
        name: my-python
        resources: {}
status: {}
